Document: telegram
Title: Debian telegram Manual
Author: <insert document author here>
Abstract: This manual describes what telegram is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/telegram/telegram.sgml.gz

Format: postscript
Files: /usr/share/doc/telegram/telegram.ps.gz

Format: text
Files: /usr/share/doc/telegram/telegram.text.gz

Format: HTML
Index: /usr/share/doc/telegram/html/index.html
Files: /usr/share/doc/telegram/html/*.html
